### ISSUE TITLE
*evtx.File.Events() method seems to be broken

### ISSUE THREAD

**Issue by steve-offutt** [0xrawsec/golang-evtx#23] opened 2020-10-28 16:30 UTC
I wanted to test the parser without the concurrency. To my surprise the `Events()` method does not return any events. I suspect this is related to the issue in the comments of `FastEvents()` method: 
```go
				// We have to create a copy here because otherwise cpc.EventsChan() fails
				// I guess that because EventsChan takes a pointer to an object and that
				// and thus the chan is taken on the pointer and since the object pointed
				// changes -> kaboom
```
While it's not a major issue, it would still be nice to have the non-concurrent version of the parser available.

**Comment by qjerome** [comment] 2020-11-05 20:16
Hey @steve-offutt ,

Sorry for the delay, finally found the time to work on this.

The issue is now fixed.

Thanks for using the library and reporting issues.

Cheers

**Closed** 2020-11-05 20:16 UTC
